### ISSUE TITLE
Unable to create oVirt template  for centos

### ISSUE THREAD

**Issue by eslutsky** [oVirt/ovirt-ansible-image-template#51]
versions:
ovirt-ansible-image-template-1.1.11-1.el7.noarch
ovirt-engine-4.3.5.4-1.el7.noarch

[root@es-engine02 ~]# ansible --version
ansible 2.8.3
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Jun 20 2019, 20:27:34) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]

Trying to run this play:
```yml
---
- name: oVirt image template
  hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
    # Contains encrypted `engine_password` varibale using ansible-vault
    - passwords.yml

  vars:
    engine_fqdn: es-engine02.lab.eng.tlv2.redhat.com
    engine_user: admin@internal
    engine_cafile: /etc/pki/ovirt-engine/ca.pem
    qcow_url: https://cloud.centos.org/centos/7/images/CentOS-7-x86_64-GenericCloud.qcow2
    template_cluster: Default
    template_name: centos2_template
    template_memory: 2GiB
    template_cpu: 4
    template_disk_size: 10GiB
    template_disk_storage: hosted_storage

  roles:
    - ovirt.image-template
```

ansible stdout:
https://paste.centos.org/view/edd12342

result error:

```log
TASK [ovirt.image-template : Create template] *********************************************************************************************************************************************************************





An exception occurred during task execution. To see the full traceback, use -vvv. The error was: Exception: Timeout exceed while waiting on result state of the entity.
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Timeout exceed while waiting on result state of the entity."}

TASK [ovirt.image-template : Remove downloaded image] *************************************************************************************************************************************************************
skipping: [localhost]

TASK [ovirt.image-template : Remove vm] ***************************************************************************************************************************************************************************
changed: [localhost]

TASK [ovirt.image-template : Logout from oVirt] *******************************************************************************************************************************************************************
ok: [localhost]

PLAY RECAP ********************************************************************************************************************************************************************************************************
localhost                  : ok=15   changed=5    unreachable=0    failed=1    skipped=12   rescued=0    ignored=0   

```
from engine logs:  https://paste.centos.org/view/5bf98741
