### ISSUE TITLE
Add support for gzipped  coreOS  qcow images

### ISSUE THREAD

**Issue by eslutsky** [oVirt/ovirt-ansible-image-template#52]
template fails if the qcow image is compressed in gzip format,
for example this image:
https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/pre-release/latest/rhcos-42.80.20190828.2-qemu.qcow2

running ansible:
```yaml
---
- name: oVirt image template
  hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
    # Contains encrypted `engine_password` varibale using ansible-vault
    - passwords.yml

  vars:
    engine_fqdn: es-engine02.lab.eng.tlv2.redhat.com
    engine_user: admin@internal
    engine_cafile: /etc/pki/ovirt-engine/ca.pem
    qcow_url: https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/pre-release/latest/rhcos-42.80.20190828.2-qemu.qcow2
    template_cluster: Default
    template_name: rchos_template
    template_memory: 6GiB
    template_cpu: 4
    template_disk_size: 40GiB
    template_disk_storage: hosted_storage

  roles:
    - ovirt.image-template
```

 result:
```log
PLAY [oVirt image template] ***************************************************************************************************************************************************************************************

TASK [ovirt.image-template : Fail when invalid parameters] ********************************************************************************************************************************************************
skipping: [localhost]

TASK [ovirt.image-template : Image upload] ************************************************************************************************************************************************************************
included: /usr/share/ansible/roles/ovirt.image-template/tasks/qcow2_image.yml for localhost

TASK [ovirt.image-template : Check if template is correct] ********************************************************************************************************************************************************
skipping: [localhost]

TASK [ovirt.image-template : Check if /tmp is directory] **********************************************************************************************************************************************************
ok: [localhost]

TASK [ovirt.image-template : Download the qcow image] *************************************************************************************************************************************************************
changed: [localhost]

TASK [ovirt.image-template : Check file type] *********************************************************************************************************************************************************************
ok: [localhost]

TASK [ovirt.image-template : Fail if image is not qcow] ***********************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "The downloaded file is not valid QCOW file."}

PLAY RECAP ********************************************************************************************************************************************************************************************************
localhost                  : ok=4    changed=1    unreachable=0    failed=1    skipped=2    rescued=0    ignored=0   

```

```shell
# file rhcos-42.80.20190828.2-qemu.qcow2
rhcos-42.80.20190828.2-qemu.qcow2: gzip compressed data, was "rhcos-42.80.20190828.2-qemu.qcow2", from Unix, last modified: Wed Aug 28 17:04:57 2019
```
